### ISSUE TITLE
fix more/related posts feed

### ISSUE THREAD

**Issue by iokouts** [iokouts/KickIt#17]
fix Page Queries that populate the Read More and Related lists with posts.

for example, in homepage we don't want to show the posts that are included in the slider (BlogPage -> show_in_homepage_slider)
https://github.com/iokouts/KickIt/blob/ce3578b58a5c9eca5c86bb6286bfc3c100dbdda6/home/models.py#L37

and

in BlogPage Related list we want to show the Posts with the biggest number of common tags
https://github.com/iokouts/KickIt/blob/ce3578b58a5c9eca5c86bb6286bfc3c100dbdda6/blog/models.py#L129

Reference:
[Wagtail Indexing](http://docs.wagtail.io/en/v2.4/topics/search/indexing.html#wagtailsearch-indexing-fields)

**Comment by glogiotatidis** [comment]
> for example, in homepage we don't want to show the posts that are included in the slider (BlogPage -> show_in_homepage_slider)

Something like this should do it

```python
 featured_posts = BlogPage.objects.live().exclude(pk__in=slider_posts).order_by('-first_published_at')[:6]
```

**Comment by glogiotatidis** [comment]
> order events by custom field 'date'

not sure which is the ask here?

**Comment by glogiotatidis** [comment]
> in BlogPage Related list we want to show the Posts with the biggest number of common tags

`taggit` has a method `similar_objects()`. Try something like 

```python
blogpages = self.tags.similar_objects()
```

docs https://django-taggit.readthedocs.io/en/latest/api.html?#TaggableManager.similar_objects

**Comment by iokouts** [comment]
> `taggit` has a method `similar_objects()`. Try something like
> 
> ```python
> blogpages = self.tags.similar_objects()
> ```

there seems to be a bug, explained here:
https://stackoverflow.com/questions/47240510/getting-related-objects-via-tags-in-django

I suppose we cannot implement the suggested solution in our project, due to deploying with docker. correct?

**Comment by iokouts** [comment]
> order events by custom field 'date'
> 
> [KickIt/event/models.py](https://github.com/iokouts/KickIt/blob/1b6b4172eb7c3ad179e937068c9e46b0b310c862/event/models.py#L26)
> 
> Line 26 in [1b6b417](/iokouts/KickIt/commit/1b6b4172eb7c3ad179e937068c9e46b0b310c862)
>  events = self.get_children().live().order_by('-first_published_at')

fixed :
`context['events'] = EventPage.objects.live().order_by('-date')`

**Comment by glogiotatidis** [comment]
> I suppose we cannot implement the suggested solution in our project, due to deploying with docker. correct?

You can either:
 - Fork taggit, path and use your own version
 - (suggested) Monkey patch `taggit.similar_objects()` when the app loads. Django's app config is a good place to monkey patch. Example https://github.com/mozilla/sugardough/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/%7B%7B%20cookiecutter.project_name%20%7D%7D/base/app.py#L9 https://docs.djangoproject.com/en/2.1/ref/applications/#configuring-applications
